

export const DifficultyValues = { "easy": "Easy", "medium": "Medium", "hard": "hard" } as const
export type Difficulty = keyof typeof DifficultyValues

export const CategoryValues = {
  "9": "Entertainment: General Knowledge",
  "10": "Entertainment: Books",
  "11": "Entertainment: Film",
  "12": "Entertainment: Music",
  "13": "Entertainment: Musicals & Theatres",
  "14": "Entertainment: Television",
  "15": "Entertainment: Video Games",
  "16": "Entertainment: Board Games",
  "17": "Science & Nature",
  "18": "Science: Computers",
  "19": "Science: Mathematics",
  "20": "Mythology",
  "21": "Sports",
  "22": "Geography",
  "23": "History",
  "24": "Politics ",
  "25": "Art",
  "26": "Celebrities",
  "27": "Animals",
  "28": "Vehicles",
  "29": "Entertainment: Comics",
  "30": "Science: Gadgets",
  "31": "Entertainment: Japanese Anime & Manga",
  "32": "Entertainment: Cartoon & Animations",
} as const
export type Category = keyof typeof CategoryValues

export const QuestionTypeValues = {
  "multiple": "Multiple Choice",
  "boolean": "True or False"

} as const
export type QuestionType = keyof typeof QuestionTypeValues

export type QuestionResponse = {
  category: string,
  correct_answer: string,
  difficulty: string,
  incorrect_answers: string[],
  question: string,
  type: string
}
export type theTriviaApiDifficulty = "easy" | "medium" | "hard"

export type theTriviaApiResponse = {
  category: string,
  id: string,
  correctAnswer: string,
  incorrectAnswers: string[],
  question: string,
  tags: string[],
  type: string,
  difficulty: theTriviaApiDifficulty,
  regions: [],
  isNiche: boolean
}


export type OpenTDBResponse = {
  response_code: number,
  results: QuestionResponse[]
}

export interface MultiSelectOption { value: string; label: string }

export type RoomData = {
  roomId?: string;
  roomName: string;
  gameId?: string;
  currentQuestion: number;
  isPublic: boolean;
  isEnded: boolean;
  isStarted: boolean;
  isShowingScoreCard?: boolean;
  roomLeaderId?: string;
  roomLeaderName?: string;
  triviaQuestions: QuestionResponse[];
};

export type answerList = {
  answer: string;
  index: number;
};


export type Player = {
  id: string;
  name: string;
  score?: 0,
  lastAnswer?: string
  correctAnswers?: string[]
  answersList?: answerList[]
};

export const theTriviaApiCategoriesValues = {
  arts_and_literature: "Arts & Literature",
  film_and_tv: "Film & TV",
  food_and_drink: "Food & Drink",
  general_knowledge: "General Knowledge",
  geography: "Geography",
  history: "History",
  music: "Music",
  science: "Science",
  society_and_culture: "Society & Culture",
  sport_and_leisure: "Sport & Leisure"
} as const

export type theTriviaApiCategories = keyof typeof theTriviaApiCategoriesValues

export type theTriviaApiQueryValues = {
  limit: number,
  categories: MultiSelectOption[],
  difficulty: theTriviaApiDifficulty,
  tags: string[],
  region: 'US',
  roomName?: string
}

export const theTriviaApiTags = [
  "00's",
  "1400's",
  "1600's",
  "1700's",
  "1800's",
  "1910's",
  "1920's",
  "1930's",
  "1940's",
  "1950's",
  "1960's",
  "1970's",
  "1980's",
  "1990's",
  "2010's",
  "academy_awards",
  "acronyms",
  "acting",
  "actors",
  "advertising",
  "africa",
  "albums",
  "alcohol",
  "american_football",
  "anatomy",
  "ancient_egypt",
  "ancient_greece",
  "animals",
  "architecture",
  "art",
  "arts_and_literature",
  "asia",
  "assassinations",
  "astronomy",
  "athletics",
  "australia",
  "baltimore",
  "bands",
  "baseball",
  "basketball",
  "batman",
  "battles",
  "biology",
  "birds",
  "bodies_of_water",
  "boston",
  "boxing",
  "bridges",
  "buddhism",
  "bugs",
  "buildings",
  "business",
  "cambodia",
  "canada",
  "capital_cities",
  "cartoons",
  "central_america",
  "cheese",
  "chemistry",
  "chicago",
  "childrens_literature",
  "china",
  "christianity",
  "christmas",
  "cities",
  "civil_rights",
  "classic_novels",
  "classical_music",
  "classics",
  "cocktails",
  "cold_war",
  "colours",
  "comics",
  "computing",
  "countries",
  "cover_song",
  "cricket",
  "crime",
  "cuba",
  "cult_films",
  "currency",
  "dallas",
  "darts",
  "dc",
  "deserts",
  "dinosaurs",
  "disney",
  "drink",
  "drinks",
  "empires",
  "europe",
  "events",
  "exploration",
  "fantasy",
  "fashion",
  "fiction",
  "fictitious_characters",
  "film",
  "film_and_tv",
  "firsts",
  "fish",
  "flags",
  "food",
  "food_and_drink",
  "football",
  "formula_1",
  "france",
  "games",
  "general_knowledge",
  "geography",
  "geology",
  "germany",
  "golf",
  "greece",
  "halloween",
  "harry_potter",
  "hinduism",
  "history",
  "hock",
  "hockey",
  "horror",
  "india",
  "initials",
  "inventions",
  "iran",
  "islam",
  "islands",
  "italy",
  "james_bond",
  "japan",
  "jazz",
  "judaism",
  "kings",
  "kpop",
  "lakes",
  "language",
  "las_vegas",
  "leaders",
  "literature",
  "liverpool",
  "logos",
  "london",
  "lord_of_the_rings",
  "lyrics",
  "manchester",
  "marketing",
  "martial_arts",
  "marvel",
  "mathematics",
  "mcu",
  "medicine",
  "medieval",
  "mediterranean",
  "meteorology",
  "middle_ages",
  "mlb",
  "mls",
  "moldova",
  "motoring",
  "motown",
  "mountains",
  "music",
  "music_albums",
  "musicals",
  "musicians",
  "mythology",
  "names",
  "natural_disasters",
  "natural_wonders",
  "nba",
  "nbl",
  "new_orleans",
  "new_york",
  "new_zealand",
  "nfl",
  "nhl",
  "nicknames",
  "numbers",
  "oceans",
  "olympics",
  "one_hit_wonders",
  "organisations",
  "painting",
  "paris",
  "pastry",
  "people",
  "philosophy",
  "physics",
  "places",
  "plants",
  "politics",
  "pop_music",
  "presidents",
  "previous_names",
  "pseudonyms",
  "quotes",
  "racing",
  "rap",
  "rap_music",
  "records",
  "religion",
  "revolutions",
  "rivers",
  "rock_music",
  "romans",
  "rugby",
  "russia",
  "salvador_dali",
  "scandinavia",
  "science",
  "science_fiction",
  "scientific_discoveries",
  "shakespeare",
  "soccer",
  "society_and_culture",
  "songs",
  "soundtracks",
  "south_america",
  "southampton",
  "southeast_asia",
  "space",
  "space_exploration",
  "spain",
  "sport",
  "star_wars",
  "statues",
  "swimming",
  "symbols",
  "technology",
  "tennis",
  "the_ancient_world",
  "the_beatles",
  "the_human_body",
  "the_internet",
  "the_middle_east",
  "the_netherlands",
  "the_simpsons",
  "the_solar_system",
  "theater",
  "tourist_attractions",
  "toys",
  "traditions",
  "translations",
  "tv",
  "uk",
  "ukraine",
  "us_states",
  "usa",
  "video_games",
  "vietnam",
  "vikings",
  "volcanoes",
  "wars",
  "waterfalls",
  "wine",
  "words",
  "world_cup",
  "world_war_1",
  "world_war_2",
  "young_adult"
]
